<!--<#import "/spring.ftl" as spring/>-->
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Error accessing Libraries Javadocs</title>
		<link rel="stylesheet" href="static/main.css">
	</head>
	<body>
		<h1>Something when wrong!</h1>
		<h2>We are lookning into it.</h2>
		<a href="/">Go Home</a>
	</body>
</html>